### ISSUE TITLE
Expand OnConflict type to express "on conflict do update"

### ISSUE THREAD

**Issue by chris-martin** [circuithub/rel8#115]
There are some things you can put in an [on conflict](https://www.postgresql.org/docs/13/sql-insert.html#SQL-ON-CONFLICT) clause that are not currently expressible with the `OnConflict` type, notably the "on conflict do update" SQL, which allows an INSERT that would violate a constraint to automatically convert into an UPDATE instead.

One example of a `postgresql-simple` query in my application that I cannot write with `rel8`:

```sql
insert into tc.stripe_invoice
    ( stripe_invoice_id
    , live_mode
    , stripe_customer_id
    , finalized_at
    , invoice_url
    )
values (?, ?, ?, ?, ?)
on conflict on constraint stripe_invoice_pkey do update
    set finalized_at = excluded.finalized_at
      , invoice_url  = excluded.invoice_url
```

It seems like it might be possible to expand rel8 to accommodate this in a type-safe way, but short of that, perhaps there could be an escape hatch here to permit writing the on-conflict clause manually?

**Comment by ocharles** [comment]
Yep, we're working on this one - https://github.com/circuithub/rel8/pull/85 should hopefully give us `UPSERT` support.

**Comment by shane-circuithub** [comment]
Closing this now that #85 has merged.
