### ISSUE TITLE
Build failures with latest opaleye (0.9.1 and 0.9.2)

### ISSUE THREAD

**Issue by chris-martin** [circuithub/rel8#167]
rel8-1.3.0.0 does not build with opaleye-0.9.1.0 (released two days ago) or opaleye-0.9.2.0 (released yesterday).

These versions are in bounds, so a metadata revision would be appropriate.

opaleye 0.9.0.0 can stay in bounds.

**Comment by ocharles** [comment]
Thanks for the ping @chris-martin - we're working on this in https://github.com/circuithub/rel8/pull/165. I'll make a revision for 1.3.0 now.

**Comment by ocharles** [comment]
I've made a revision for 1.3.0 to add `opaleye < 0.9.1.0`. I'll go ahead and close this, as we already have support for 0.9.1.0+ in `HEAD` (due to be released Friday)
