### ISSUE TITLE
Documentation should mention that some queries generated by `rel8` have an implicit dependency on postgres versions >= 12

### ISSUE THREAD

**Issue by ixmatus** [circuithub/rel8#203]
Specifically I encountered some queries generated by `rel8` that work fine on versions of postgres >= 12 but that fail at least on postgres 9.6 (I did not test intermediate versions between 9.6 and 12) with: `record type has not been registered`. This looks like it is due to some queries that use `ROW`.

I'm happy to add documentation myself or figure out what changed in which version that make these queries work but thought I'd at least create an issue to track this or help others discover it.

**Comment by shane-circuithub** [comment]
This will have been fixed by #242. The next release of Rel8 won't use `ROW` in those situations anymore.
