### ISSUE TITLE
Decimal type ?

### ISSUE THREAD

**Issue by revskill10** [circuithub/rel8#218]
Could we map `decimal(x,y)` from PostgreSQL type to Haskell type with Rel8 ?

**Comment by ocharles** [comment]
Yes, but I'm not entirely sure if there is a corresponding Haskell type.

**Comment by shane-circuithub** [comment]
[`Fixed`](https://hackage.haskell.org/package/base-4.18.0.0/docs/src/Data.Fixed.html#Fixed) seems like the obvious choice to me.

**Comment by shane-circuithub** [comment]
Fixed by #280
