### ISSUE TITLE
Allow hedgehog 1.2 in test suite

### ISSUE THREAD

**Issue by sternenseemann** [circuithub/rel8#248]
That version is now shipped with Stackage LTS 21. The test suite builds and passes for me with said hedgehog version, so a hackage revision would be appreciated!

**Comment by ocharles** [comment]
I'm happy to bump this, but why do you need a Hackage revision? Rel8 only uses Hedgehog for its test suite, so this version shouldn't matter for normal development. Does Stack run tests or something?

**Comment by sternenseemann** [comment]
stack does not (Stackage would, but that's not relevant here I believe), but nixpkgs does. A revision is not strictly necessary, but it's usually helpful to be able to clean up constraint-related workarounds.

**Comment by ocharles** [comment]
Ah, yes, nixpkgs runs tests. Cool, well either way - this should be done! Thanks for the issue.

**Comment by shane-circuithub** [comment]
This was fixed in #278.
