### ISSUE TITLE
Can we get `nullify :: Expr a -> Expr (Maybe a)`

### ISSUE THREAD

**Issue by ocharles** [circuithub/rel8#25]
Currently there is an extra `IsMaybe a ~ False`. This looks obvious to me, and I wonder if we can somehow show GHC that.

**Comment by shane-circuithub** [comment]
`IsMaybe a ~ 'False` is necessary to forbid the construction of `Maybe (Maybe a)`. But #23 might at least make this nicer cosmetically.
