### ISSUE TITLE
Release a version compatible with `opaleye-0.10.2.0`

### ISSUE THREAD

**Issue by tomjaguarpaw** [circuithub/rel8#288]
For https://github.com/Zelenya/elephants/pull/5 I need a version of `rel8` on Hackage that is compatible with `opaleye-0.10.2.0`. GitHub `master` supports it, but Hackage is stuck on `0.9.x`. Could you please release a compatible version of `rel8`? (Maybe just revising Hackage bounds would be enough, I'm not sure.)

**Comment by ocharles** [comment]
Not quite what you're asking, but https://hackage.haskell.org/package/rel8-1.5.0.0 supports 0.10.2.1, so I'm going to call this done.
