### ISSUE TITLE
New Hackage release?

### ISSUE THREAD

**Issue by elldritch** [circuithub/rel8#293]
I love the additions you've made into `master`, especially the fix for https://github.com/circuithub/rel8/issues/228. Any timeline on when those might show up on Hackage?

My main use case is that I'd like to be able to see the rendered Haddock on the package site. My team is currently using a commit off of `master`, and newbies occasionally trip over the outdated documentation.

**Comment by ocharles** [comment]
I think we're well overdue for a release, and I'll try and see if I can cut one in the next few days. Thanks for the nudge!

**Comment by seanhess** [comment]
The current release is not compiling on ghc 9.8 due to the upper bound on base (<4.18)
