### ISSUE TITLE
Bad escaping of lambdas in Haddocks

### ISSUE THREAD

**Issue by georgefst** [circuithub/rel8#315]
<img width="549" alt="image" src="https://github.com/circuithub/rel8/assets/12991097/39be2942-b248-4b42-990e-467548082f6e">

**Comment by abigailalice** [comment]
The stuff on construction also has examples of this, showing value applications when they should have type applications

```
> :t buildADT Task "Pending"
buildADT Task "Pending" :: ADT Task Expr
> :t buildADT Task "Complete"
buildADT Task "Complete" :: CompletedTask Expr -> ADT Task Expr
```

**Comment by ocharles** [comment]
@abigailalice Am I right in thinking you fixed this?

**Comment by abigailalice** [comment]
I found at least one more example, I'm going through things thoroughly to see if there are any more.
