### ISSUE TITLE
Support hasql-1.8

### ISSUE THREAD

**Issue by TeofilC** [circuithub/rel8#341]
hasql-1.8 switches the ip address package from network-ip to iproute this breaks our instance for the IP address type.

We could either switch as well, or we could expose instances for both types

**Comment by ocharles** [comment]
If it's not too much work to support both it feels nice to avoid a breaking change

**Comment by TeofilC** [comment]
Yes I agree. I guess adding another dependency isn't too bad. Both of these packages are relatively small

**Comment by andremarianiello** [comment]
I am suffering from this right now, so I am seeing how difficult support for 1.8 would be to add. When this is done, do you want to keep support for hasql-1.6 and hasql-1.7? Since the `Hasql.inet` decoder changed in 1.8, this would require CPP (I think) to support both versions. Is this okay?

**Comment by TeofilC** [comment]
I have a draft branch here https://github.com/circuithub/rel8/pull/345

I just need to test/double check some of this code.

If you could help test it that would be great!

**Comment by andremarianiello** [comment]
Unfortunately I am not sure how to test this either.

**Comment by TeofilC** [comment]
No worries. I should have the patch done soon anyway
