### ISSUE TITLE
`JSONEncoded` produces `jsonb` rather than the documented `json`

### ISSUE THREAD

**Issue by jy14898** [circuithub/rel8#344]
It seems to delegate to `Aeson.Value`'s `DBType` via `parseJSON`/`toJSON`, but `Aeson.Value`'s `DBType` is `jsonb`. This means (as far as I can tell) the behaviour is the same as `JSONBEncoded`.

**Comment by jy14898** [comment]
For now we've fixed this by using the below wrapper, as they both have the same encoded representation

```haskell
newtype RawValue = RawValue {getRawValue :: Aeson.Value}

-- | Corresponds to @json@
instance DBType RawValue where
  typeInformation = TypeInformation
    { encode = (typeInformation @Aeson.Value).encode . (.getRawValue)
    , decode = RawValue <$> Hasql.json
    , typeName = "json"
    }
```

**Comment by jy14898** [comment]
To add some context, the mismatch of json vs jsonb didn't matter until rel8 generated a CASE expression with different types in either case (one from the real json column, and one an empty array of jsonb). Postgres errors out as it requires the two cases to have the same type

**Comment by TeofilC** [comment]
This does sound like an oversight. Would you be willing to make a PR @jy14898 ?
