### ISSUE TITLE
not compatible with hqsql-1.8 etc

### ISSUE THREAD

**Issue by ysangkok** [circuithub/rel8#351]
Stackage Nightly now contains:

```
        - rel8 < 0 # tried rel8-1.5.0.0, but its *library* requires base ^>=4.16 || ^>=4.17 || ^>=4.18 || ^>=4.19 and the snapshot contains base-4.20.0.0
        - rel8 < 0 # tried rel8-1.5.0.0, but its *library* requires base-compat ^>=0.11 || ^>=0.12 || ^>=0.13 and the snapshot contains base-compat-0.14.1
        - rel8 < 0 # tried rel8-1.5.0.0, but its *library* requires hasql ^>=1.6.1.2 and the snapshot contains hasql-1.8.1.3
```

While e.g. the hqsql bump seems to be high enough in Git, it still says `<1.7` on Hackage.

**Comment by TeofilC** [comment]
@ocharles @shane-circuithub would one of you like to make a release? If not I'd be happy to cut one. Just add my Hackage user ([teo](https://hackage.haskell.org/user/teo)) to the maintainers group and I'll make one in the next few days

**Comment by ocharles** [comment]
@TeofilC Happy to leave this with you! Note that I was trying to use `scriv` to manage the changelog, so you might want to look that up.

**Comment by ocharles** [comment]
You're added to the Hackage maintainers group now

**Comment by TeofilC** [comment]
I have released https://hackage.haskell.org/package/rel8-1.6.0.0, which has the hasql bound bump
