### ISSUE TITLE
Wherefore the `c` in the docs?

### ISSUE THREAD

**Issue by masaeedu** [circuithub/rel8#64]
Hello there. I really enjoyed the talk on rel8 from Zurihac and am currently excitedly reading documentation. I noticed something a bit confusing in the [tutorial section](https://rel8.readthedocs.io/en/latest/tutorial.html):

![image](https://user-images.githubusercontent.com/3674056/122681622-c3a43780-d1e4-11eb-8652-1b36cc6851ae.png)

There's a `c` argument that shows up seemingly without further explanation in the docs. From reading the Hackage docs I can see this is supposed to be the database connection, but I think it'd be handy to mention this at least in passing. Alternatively, you could just name it more suggestively: `conn` or `connection` or whatever.

**Comment by ocharles** [comment]
Thanks for the kind words @masaeedu! I agree this could be clearer. I'll expand this section now.
