### ISSUE TITLE
Showing the query for insert/update/delete

### ISSUE THREAD

**Issue by chris-martin** [circuithub/rel8#80]
Would it be possible to add functions like `showQuery`, but for operations other than select?

A couple reasons:

  - At the moment I would like it because I'm curious about how the `update` function works (what does the query look like when you don't update all of the columns?).
  - I think I might like to start logging queries at some point.

**Comment by ocharles** [comment]
Great idea! For now I think we can add `showInsert`, `showUpdate`, and `showDelete`.

**Comment by shane-circuithub** [comment]
Closing this now that #85 has merged.
