### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by ocharles** [circuithub/rel8#95]

**Comment by ocharles** [comment]
https://github.com/commercialhaskell/stackage/pull/6095

**Comment by sternenseemann** [comment]
What are you plans wrt a new release supporting opaleye 7.3.0? Seems like stackage is blocking on that and we are also running into this in nixpkgs at the moment as we track opaleye from stackage. Unfortunately there doesn't seem to be a single commit from master we can apply as a patch to get it building as well.

**Comment by ocharles** [comment]
We have a few more breaking changes (all in open PRs). I'm hoping we will have a new release by next Friday 🤞

**Comment by ocharles** [comment]
Done! @sternenseemann not sure if you can do anything with nixpkgs atm, but we'll stay in Stackage from now on.

**Comment by sternenseemann** [comment]
1.1.0.0 fixed our opaleye trouble, ty :)
